[Upgrade] melhoria visual na tela do questionário
Engenharia-de-Software-UFRPE/lanterna-verde pull request #85
Opened 2022-10-09 20:02 UTC by multi-megaman

Nessa Pull Request foi implementado a melhoria visual requisitada na issue #82

## Problema

O problema se dava devido ao fato da tela para fazer a análise e visualizar análises já feita não estavam visualmente agradáveis.
## Implementação

## Como Testar

Basta ir em uma das telas (fazer análise ou a tela de visualizar uma nálise já finalizada) e ver as melhorias, testas os botões, ver a interface e confirmar se as informações ainda estão sendo salvas no backend da maneira correta.

![image](https://user-images.githubusercontent.com/84993974/194777066-e4d7ab56-d321-474c-b27e-db2f4e6e78ce.png)

## Objetivos

Fix #82

2022-10-10 20:58 UTC, SteffanoP requested changes
Olá @multi-megaman! Muito Obrigado por estar contribuindo!

Aqui vão alguns detalhes que eu acredito que podem ser melhorados:

- Senti falta da documentação sobre como foi feita a implementação;
- Está faltando os ícones do Figma de Aceitação (Sinal de Correto) e Negação (Sinal de Erro);
  - Exportei os ícones no formato svg logo abaixo
- Você poderia centralizar o texto e colocar as perguntas no meio da caixa (algo como `center-center`, ao invés de `top-center`), além disso, acho interessante aumentar o tamanho da fonte para compreender toda a caixa de pergunta;
- Também verifiquei que a animação do botão sai do meio e não necessariamente daonde ele estava inicialmente, conforme o [vídeo](https://user-images.githubusercontent.com/26782009/194950761-393c7be0-3507-419b-8182-e165292c447d.webm), perceba o teletransporte.

Creio que se você puder trabalhar nesses pontos, teremos uma implementação perfeita!

<details>
<summary>Ícones</summary>

![Accept Icon](https://user-images.githubusercontent.com/26782009/194949397-5a2e2080-65c3-4607-8e5f-fb85b1b9db34.svg)

![Deny Icon](https://user-images.githubusercontent.com/26782009/194949504-e55d8289-094d-4c05-b225-70f0b667cad5.svg)
</details>

2022-10-19 13:55 UTC, multi-megaman commented
Vou trabalhar nessas melhorias agora msm!

2022-10-19 14:48 UTC, multi-megaman commented
Pronto as alterações foram feitas

2022-10-19 17:27 UTC, multi-megaman commented
Verdade, vou ajustar agora.

2022-10-19 17:33 UTC, multi-megaman commented
Pronto, as alterações foram feitas também na Tela Questionário finalizado.

2022-10-20 02:20 UTC, SteffanoP requested changes
@multi-megaman Ainda estou verificando algumas inconsistências quanto ao tamanho da box ocorrendo na Tela de Questionário finalizada, dê uma olhada no seguinte:

### Tela de Questionário em andamento

![image](https://user-images.githubusercontent.com/26782009/196840609-3eb1153f-d2f4-4f9a-ba37-b540dd1baf46.png)

### Tela do Questionário finalizado

![image](https://user-images.githubusercontent.com/26782009/196840647-d2f30c4b-b895-437f-955d-d749c45d29f5.png)

Caso você já tenha corrigido esse problema na PR #87, por favor, me avise; caso contrário fico no aguardo da sua implementação de correção.

2022-10-20 17:44 UTC, multi-megaman commented
O problema já foi resolvido na PR #87 como é possível observar na imagem da tela que mostra uma análise finalizada:

![image](https://user-images.githubusercontent.com/84993974/197020572-e7ff9449-43ca-44f3-96d7-12d5025d2be9.png)

2022-10-20 18:15 UTC, SteffanoP approved these changes
Massa! Suas implementações estão ótimas e agradeço imensamente pela contribuição! 🚀 🚀

2022-10-20 18:15 UTC, merged