[Feature] Barra de progresso implementada e opção de questão não respondida
Engenharia-de-Software-UFRPE/lanterna-verde pull request #94
Opened 2022-10-24 14:59 UTC by multi-megaman

Nessa Pull Request foi implementada a barra de progresso na tela do preenchimento do questionário por parte do analista para que ele possa ter uma noção de quantas perguntas faltam para que ele responda todas as questões:
![image](https://user-images.githubusercontent.com/84993974/197547617-cc759acd-c4cd-4444-b29a-7d241cdb88fc.png)

## Problema

O problema é que atualmente, o analista não tem nenhuma dica ou indicação visual do seu progresso em uma análise específica, isso fazia com que o progresso do preenchimento do formulário pudesse ser facilmente esquecido pelo analista, já que ele não teria nenhum recurso visual que o indicasse o quanto ainda lhe faltava para a finalização de uma análise.

## Implementação

Antes de mais nada, vale apontar que foram necessários alguns ajustes no backend do projeto, para que fosse possivel a adequação das novas features no projeto. Primeiramente o modelo da questão foi alterado, onde o atributo "answer" da mesma, passou de um booleano para um inteiro, podendo receber três valores diferentes, sendo eles (0, 1, 2) onde eles representam, respectivamente (resposta negativa, resposta positiva, ainda não respondido) poís existia essa necessidade de saber quando uma resposa foi respondida ou não, além claro de saber qual foi a resposta dada pelo analísta. A modificação foi a seguinte:
![image](https://user-images.githubusercontent.com/84993974/197549169-3343f42d-9910-4d94-8571-e429d34df056.png)
Para:
![image](https://user-images.githubusercontent.com/84993974/197549272-133d24a7-93af-41aa-b6f7-f65278ef8aaa.png)

Também foi necessário mudar o valor padrão das respostas de cada pergunta, passando de "false" (ou seja, por padrão todas as respostas eram marcadas como negativas) para o valor 2 (ou seja, "not_answered"):
![image](https://user-images.githubusercontent.com/84993974/197549948-3e7b95a7-bfea-4fc5-a308-ce14d4b76526.png)

Também foi necessário fazer uma pequena modificação no backend no arquivo countdimension.py para que a contagem das dimensões fosse feita de forma correta, para isso apenas modifiquei a condicional, onde agora só seria contabilizado caso a resposta fosse igual a 1 (o que indicaria que a pergunta foi respondida positivamente):
![image](https://user-images.githubusercontent.com/84993974/197550405-88e755bf-af4a-4270-90ca-0e2500763604.png)

Já na parte do frontend, algumas coisas foram adicionadas e alteradas. Primeiramente a barra de progresso que foi utilizada foi a ProgressBar do proprio react. Nessa parte não houve nenhuma dificuldade de implementa-lá, já que é apenas um componente já montado. Agora para a utilização do valor que será introduzido na barra, foi necessário a adição de um novo state chamado "analysisCountRate" que sempre será calculado da seguinte forma:
((Numero de questões respondidas) / (Numero total de questões)) * 100)
![image](https://user-images.githubusercontent.com/84993974/197551152-7cf5aab5-6ed9-4dc0-b0f8-2c325dccd121.png)

Que resulta em:
![image](https://user-images.githubusercontent.com/84993974/197551286-b1d0d48e-02ca-4e56-9372-00dfe00224c9.png)

## Como Testar
Antes de mais nada, como foram necessários algumas alterações no backend, sugiro que delete sua base de dados anterior e faça as migrações necessárias do Django com os seguintes comandos:
  python manage.py makemigrations
  python manage.py migrate --run-syncdb

E em seguida faça os comandos padrões antes de iniciar o servidor:
  python manage.py createsuperuser
  python manage.py runscript populate_gas_questions
  python manage.py runserver

Primeiramente faça login como analista e abra uma das suas analises ainda não finalizada e veja se a nova barra de progresso aparece para você. Você deve ver algo parecido com isto:
![image](https://user-images.githubusercontent.com/84993974/197552334-6ddde68d-54b3-4c5c-ab76-839cbc902283.png)

Agora note também que, as questões que você ainda não respondeu, não estão nem para a direita nem para a esquerda, e sim no centro, indicando que ainda não foram respondidas:

![image](https://user-images.githubusercontent.com/84993974/197552498-3f064181-bbb9-4288-a42b-44e171eebfde.png)

Agora selecione as respostas das questões ainda não respondidas e veja se a barra de progresso aumenta a medida que você as responde, de maneira semelhante ao GIF abaixo: 

## Notas do desenvolvedor

Foram necessárias alterações e adições tanto no frontend quanto no backend.

## Objetivos

Fix #83 
Fix #93

2022-10-24 23:51 UTC, SteffanoP requested changes
Opa @multi-megaman sua implementação é SENSACIONAL!

Estava testando por aqui e parece tudo em ordem! Porém notei que é possível Finalizar a avaliação de analista com respostas não respondidas, e quando realiza a contagem por meio da função `count_dimension` essas respostas são tratadas como negativas. Esse é um comportamento não esperado pelo sistema e precisa ser trabalhado; é interessante incluir um aviso que não é possível finalizar enquanto o Analista não responder o questionário como um todo.

Também é importante que a view de back-end esteja pronta para trabalhar com requisições inválidas, porém, nesse ponto podemos tratar em outra Issue.

Fico no aguardo do seu feedback! Happy Coding! 🚀

2022-10-25 00:18 UTC, multi-megaman commented
Olá meu patrão, vou tentar implementar isso para que o analísta não possa finalizar uma análise que não está 100%, sei que isso é lógico mas não me lembro dessa parte na issue, falha minha. Também verei o count_dimension para arrumar este problema, mandarei o feedback assim que possivel!

2022-10-25 00:37 UTC, SteffanoP commented
> Olá meu patrão, vou tentar implementar isso para que o analísta não possa finalizar uma análise que não está 100%, sei que isso é lógico mas não me lembro dessa parte na issue, falha minha. Também verei o count_dimension para arrumar este problema, mandarei o feedback assim que possivel!

Fica tranquilo quanto ao back-end! Por hora está servindo para as nossas necessidades, mas preciso que finalize apenas quando todas as respostas não forem de índice 2 (aka. Não Respondida).

2022-10-25 11:47 UTC, multi-megaman commented
Prontinho, agora o analista só consegue finalizar a análise se ela estiver 100%!

2022-10-25 11:56 UTC, multi-megaman commented
Segue um exemplo de como o analista não é capaz de finalizar a análise que ainda possui questões a serem respondidas:
![not-finished-yet 00_00_00-00_00_30](https://user-images.githubusercontent.com/84993974/197767076-58f0aef4-eae2-4291-a131-3d8bfe57a816.gif)

2022-10-26 01:02 UTC, SteffanoP approved these changes
Perfeição é a palavra certa! Muito obrigado mais uma vez @multi-megaman!

2022-10-26 01:02 UTC, merged