[Feature] Notícias
Engenharia-de-Software-UFRPE/lanterna-verde pull request #97
Opened 2022-10-27 16:10 UTC by ronaldo26rodrigues

Um dos requisitos iniciais do projeto foi um mural de notícias, onde as empresas poderiam publicar manchetes mostrando ações e campanhas sobre Greenwashing e meio ambiente para que os clientes e qualquer um que acesse nosso portal possam conhecer melhor as empresas que recebem nossas análises e acompanharem as ações em prol da sustentabilidade. Esta Pull Request implementa  as rotas e funções da API que gerenciam estas notícias

## Implementação

### O Model News
- Title: é o título da notícia
- Abstract: um breve resumo da manchete
- Creation Date: data em que a notícia foi publicada
- Edit Date: data da última modificação
- Company: empresa que publicou a manchete
- [Slug](https://www.semrush.com/blog/what-is-a-url-slug/?kw=&cmp=BR_POR_SRCH_DSA_Blog_EN&label=dsa_pagefeed&Network=g&Device=c&utm_content=622460808681&kwid=dsa-1753200729493&cmpid=18361973175&agpid=144288924871&BU=Core&extid=54841568730&adpos=&gclid=EAIaIQobChMI363bnd6A-wIV80FIAB2WLgT-EAAYASAAEgIKOvD_BwE): é uma breve frase aparece na url da notícia, facilitando a indexação e a identificação da notícia pelo usuário ao receber e abrir a notícia. Aqui, o slug é gerado a partir do título
- Body: o corpo da notícia, com o texto de tudo que a empresa quer informar

### Rotas da API
__*partes dinâmicas da URL ficam entre <>*__
- `noticia/list`: lista todas as notícias
- `noticia/list/<amount>`: lista uma certa quantidade de notícias (amount: quantidade de notícias)
- `noticia/add`: cria uma nova notícia | JSON - {title, abstract, body} (o usuário logado precisa ser uma empresa)
- `noticia/update`: edita uma notícia| JSON - {newsid, title, abstract, body} (o usuário logado precisa ser a empresa que publicou a notícia)
- `noticia/company/<company>`: lista as notícias de uma empresa (company: id da empresa)
- `noticia/<company>/<slug>`: detalha uma notícia, este é o caminho direto para ela (company: id da empresa, slug: slug da notícia)

## Como Testar

[Pacote Postman com algumas requisições configuradas](https://www.getpostman.com/collections/a687e76494bf4d765a57)

## Notas do desenvolvedor

Esta feature ainda pode evoluir muito mais, podendo encontrar uma forma de adicionar imagens e outros tipos de estilização para o corpo da notícia ficar ainda mais rico.

Também é necessário que o front-end possa direcionar corretamente as páginas de detalhes da notícia, já que os links para as noticias da api são dinâmicos, o front também deve acompanhar esta função, já que facilita para quem está recebendo a notícia e ajuda na descoberta em mecanismos de busca

2022-10-28 00:00 UTC, SteffanoP requested changes
Muito Massa sua contribuição @ronaldo26rodrigues!! 

Fiquei com dúvida de algumas coisinhas, inicialmente havíamos pensado que poderíamos publicar notícia, porém não chegamos a uma conclusão de quem iria publicar a notícia. Ao meu ver, acredito que quem iria postar as notícias seriam os administradores, poderia ser um gerente de notícias. Vou tirar a dúvida com o PO (@marcelomarinho) se o responsável por publicar a notícia seria o Administrador ou a Empresa.

Além disso fiz pequenos comentários pontuais de inconsistências no código

2022-10-31 14:50 UTC, ronaldo26rodrigues commented on lanternaverde_web/models.py
> +    company = models.ForeignKey(Empresa, related_name='noticias', on_delete=models.CASCADE)
Justíssimo, a lanterna verde também pode publicar notícias que nada tem a ver com nenhuma empresa cadastrada, de fato

2022-10-31 15:18 UTC, ronaldo26rodrigues commented
Massa, @SteffanoP, quando fiz essa solução cheguei a pensar em quem teria essa responsabilidade, e acabei deixando por conta da empresa, mas como ainda temos esse questionamento, modifiquei para que tanto empresa quanto administrador pudessem publicar, nesse caso, se a empresa faz a requisição, a notícia é associada a ela, se o administrador faz, ele pode ou não fornecer o ID da empresa.

2022-10-31 15:18 UTC, ronaldo26rodrigues commented
Também percebi que um método não pode ser acessado por mais de um tipo de usuário, então não consegui liberar o acesso para empresa e administrador ao mesmo tempo usando os decorators, e assim o método não funciona 100% como planejado se estiver restringindo o acesso. Imagino que isso seja uma coisa a ser verificada, acho que vale uma issue ;)

2022-10-31 16:12 UTC, SteffanoP approved these changes
Obrigado pela contribuição @ronaldo26rodrigues! 🚀 🚀

2022-10-31 16:13 UTC, merged